import type { InstrumentClass } from './types';

// IMPORTANT: ids are stable ASCII slugs used as i18n key suffixes
// (savings.classes.<id>.{name|taxNote|riskNote}). Do not rename.
// cbrOffset values are percentage points relative to the user's CBR snapshot.
export const INSTRUMENT_CLASSES: readonly InstrumentClass[] = [
  {
    id: 'savings_account',
    liquidity: 'daily',
    cbrOffset: { low: -3, high: -1 },
    currency: 'RUB',
    isDeposit: true,
    applicableLayers: ['A'],
    applicableRegimes: ['high', 'moderate', 'low'],
  },
  {
    id: 'term_deposit',
    liquidity: 'fixed-term',
    cbrOffset: { low: -0.5, high: 1.5 },
    currency: 'RUB',
    isDeposit: true,
    applicableLayers: ['A', 'B'],
    applicableRegimes: ['high', 'moderate'],
  },
  {
    id: 'mm_fund',
    liquidity: 'daily',
    cbrOffset: { low: -1, high: -0.5 },
    currency: 'RUB',
    isDeposit: false,
    applicableLayers: ['A', 'B'],
    applicableRegimes: ['high', 'moderate', 'low'],
  },
  {
    id: 'ofz_pd',
    liquidity: 'secondary-market',
    cbrOffset: { low: -1, high: 0.5 },
    currency: 'RUB',
    isDeposit: false,
    applicableLayers: ['B', 'C'],
    applicableRegimes: ['high'],
  },
  {
    id: 'ofz_pk',
    liquidity: 'secondary-market',
    cbrOffset: { low: -0.5, high: 0.5 },
    currency: 'RUB',
    isDeposit: false,
    applicableLayers: ['B', 'C'],
    applicableRegimes: ['moderate', 'low'],
  },
  {
    id: 'ofz_in',
    liquidity: 'secondary-market',
    cbrOffset: { low: -7, high: -4 },
    currency: 'RUB',
    isDeposit: false,
    applicableLayers: ['C'],
    applicableRegimes: ['high', 'moderate', 'low'],
  },
  {
    id: 'corp_bond',
    liquidity: 'secondary-market',
    cbrOffset: { low: 0.5, high: 2 },
    currency: 'RUB',
    isDeposit: false,
    applicableLayers: ['B', 'C'],
    applicableRegimes: ['high', 'moderate'],
  },
  {
    id: 'replacement_bond',
    liquidity: 'secondary-market',
    cbrOffset: { low: -10, high: -7 },
    currency: 'USD-settled',
    isDeposit: false,
    applicableLayers: ['C'],
    applicableRegimes: ['moderate', 'low'],
  },
  {
    id: 'cny_bond',
    liquidity: 'secondary-market',
    cbrOffset: { low: -10, high: -7 },
    currency: 'CNY',
    isDeposit: false,
    applicableLayers: ['C'],
    applicableRegimes: ['moderate', 'low'],
  },
  {
    id: 'gold',
    liquidity: 'secondary-market',
    cbrOffset: { low: -16, high: -2 },
    currency: 'Gold',
    isDeposit: false,
    applicableLayers: ['C'],
    applicableRegimes: ['high', 'moderate', 'low'],
  },
];
